version: "2.29.1"

services:
  db:
    image: postgres:16
    
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
volumes:
  postgres_data:
